<?php

/**
 * @file
 * Install, uninstall and update hooks for lupus_decoupled_menu module.
 */

use Drupal\user\Entity\Role;

/**
 * Add config for rest_menu_items.
 */
function lupus_decoupled_menu_install() {
  // Grant permissions for accessing the API.
  $role = Role::load('anonymous');
  $role->grantPermission('restful get rest_menu_item');
  $role->save();
  $role = Role::load('authenticated');
  $role->grantPermission('restful get rest_menu_item');
  $role->save();
}
